fix: or syntax

diff --git a/helm-branches.yaml b/helm-branches.yaml
--- a/helm-branches.yaml
+++ b/helm-branches.yaml
@@ -71,12 +71,12 @@ deploy:quality:helm:branches:
           fi
         done
         if [ -z "$(no_db)" ]; then
-          mysql -u$DB_USERNAME -p$DB_PASSWORD -hDBHOST -e "USE $DB_NAME" || { echo 'DB login failed! Please check credentials' ; exit 1; }
-          mysql -u$DB_USERNAME -p$DB_PASSWORD -hDBHOST -e "CREATE DATABASE $DB_NAME_$APP_BRANCH_NAME;" || { echo 'DB creation failed! Please check user permission, must have CREATE, REFERENCES and DROP' ; exit 1; }
-          mysqldump -u$DB_USERNAME -p$DB_PASSWORD -hDBHOST $DB_NAME --opt --single-transaction --skip-add-locks | mysql -u$DB_USERNAME -p$DB_PASSWORD -hDBHOST --max_allowed_packet=32M $DB_NAME_$APP_BRANCH_NAME || { echo 'DB cloning failed!' ; exit 1; }
+          mysql -u$DB_USERNAME -p$DB_PASSWORD -hDBHOST -e "USE $DB_NAME" || echo 'DB login failed! Please check credentials' ; exit 1;
+          mysql -u$DB_USERNAME -p$DB_PASSWORD -hDBHOST -e "CREATE DATABASE $DB_NAME_$APP_BRANCH_NAME;" || echo 'DB creation failed! Please check user permission, must have CREATE, REFERENCES and DROP' ; exit 1;
+          mysqldump -u$DB_USERNAME -p$DB_PASSWORD -hDBHOST $DB_NAME --opt --single-transaction --skip-add-locks | mysql -u$DB_USERNAME -p$DB_PASSWORD -hDBHOST --max_allowed_packet=32M $DB_NAME_$APP_BRANCH_NAME || echo 'DB cloning failed!' ; exit 1;
         fi
       else
-        eval(echo $URL | awk -v branch_name="$APP_BRANCH_NAME" -F [\/:@?] '{print "mysql -u" $4 " -p" $5 " -h" $6 " -e" " \x27" "CREATE DATABASE " "\x60" $8"_"branch_name "\x60" "\x27" " ; mysqldump -u" $4 " -p" $5 " -h" $6 " " $8 " --opt --single-transaction --skip-add-locks | mysql -u" $4 " -p" $5 " -h" $6 " --max_allowed_packet=32M " $8"_"branch_name}') || { echo 'DB cloning failed with URL! Please check credentials' ; exit 1; } 
+        eval(echo $URL | awk -v branch_name="$APP_BRANCH_NAME" -F [\/:@?] '{print "mysql -u" $4 " -p" $5 " -h" $6 " -e" " \x27" "CREATE DATABASE " "\x60" $8"_"branch_name "\x60" "\x27" " ; mysqldump -u" $4 " -p" $5 " -h" $6 " " $8 " --opt --single-transaction --skip-add-locks | mysql -u" $4 " -p" $5 " -h" $6 " --max_allowed_packet=32M " $8"_"branch_name}') || echo 'DB cloning failed with URL! Please check credentials' ; exit 1;
       fi
   only:
     - merge_requests
