Fix Prettier and Lint Defaults

diff --git a/lint-generic.yml b/lint-generic.yml
--- a/lint-generic.yml
+++ b/lint-generic.yml
@@ -9,7 +9,13 @@ lint:
 
   variables:
     GIT_STRATEGY: none
-    APP_LINT_COMMAND: ">&2 echo 'ERROR: APP_LINT_COMMAND Variable not set. Please set the Linting Command to be executed by this Job.' ; exit 1"
+    APP_LINT_COMMAND_DEFAULT: ">&2 echo 'ERROR: APP_LINT_COMMAND Variable not set. Please set the Linting Command to be executed by this Job.' ; exit 1"
 
   script:
-    - eval "${APP_LINT_COMMAND}"
+    - COMMAND="${APP_LINT_COMMAND_DEFAULT}"
+
+      if [ -n "${APP_LINT_COMMAND}" ]; then
+        COMMAND="${APP_LINT_COMMAND}"
+      fi
+
+      eval "${COMMAND}"
diff --git a/prettier-generic.yml b/prettier-generic.yml
--- a/prettier-generic.yml
+++ b/prettier-generic.yml
@@ -9,7 +9,13 @@ prettier:
 
   variables:
     GIT_STRATEGY: none
-    APP_PRETTIER_COMMAND: ">&2 echo 'ERROR: APP_PRETTIER_COMMAND Variable not set. Please set the Prettier Command to be executed by this Job.' ; exit 1"
+    APP_PRETTIER_COMMAND_DEFAULT: ">&2 echo 'ERROR: APP_PRETTIER_COMMAND Variable not set. Please set the Prettier Command to be executed by this Job.' ; exit 1"
 
   script:
-    - eval "${APP_PRETTIER_COMMAND}"
+    - COMMAND="${APP_PRETTIER_COMMAND_DEFAULT}"
+
+      if [ -n "${APP_PRETTIER_COMMAND}" ]; then
+        COMMAND="${APP_PRETTIER_COMMAND}"
+      fi
+
+      eval "${COMMAND}"
